# Generated by Django 3.0.8 on 2020-07-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_pictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_Pictures',
            new_name='Profile',
        ),
    ]
